### PR TITLE
Update endpoint domains to match `gsm.mapping@fix-50`

### LINKED ISSUE #42: Update endpoints domains with raw+ column names
gsm.mapping branch `fix-50` displays the new mapping files that will be used for gsm.endpoints mapping workflows. Update datasim domains to match these new column names.

### PR DESCRIPTION
**Pull request by lauramaxwell**
Updates the endpoint domain functions to match the column names used in gsm.mapping branch `fix-50`

Closes #42

### CODE REVIEW

File: R/generate_rawdata_for_single_study.R
Comment (zdz2101) [inline R/generate_rawdata_for_single_study.R:1]: Perhaps in `inst/examples/check_iterative_run.R`, add this chunk somewhere (this is working for me, successfully) investigating the "does it kinda make sense/have enough complexity" for our usecase aspect now:
```
endpoint_mappings <- c("AntiCancer", "Baseline", "Consents", "Death", "OverallResponse", 
                       "Randomization", "STUDCOMP", "Visist")

single_result_endpoints <- generate_rawdata_for_single_study(SnapshotCount = 3,
                                                   SnapshotWidth = "months",
                                                   ParticipantCount = 50,
                                                   SiteCount = 5,
                                                   StudyID = "ABC",
                                                   workflow_path = "workflow/1_mappings",
                                                   mappings = endpoint_mappings,
                                                   package = "gsm.mapping",
                                                   desired_specs = NULL)
```
@lauramaxwell

File: R/Raw_OverallResponse.R [hunk 1]
```diff
@@ -44,9 +44,9 @@ Raw_OverallResponse <- function(data, previous_data, spec, ...) {
 response_folder <- function(n, ...) {
   rep("final response", n, replace = TRUE)
 }
-response <- function(n, ...) {
+ovrlresp <- function(n, ...) {
```
Comment (zdz2101) [inline R/Raw_OverallResponse.R:47]: This was probably the domain I had a hard time rendering to produce something "worthwhile" because you would want a handful of responses for each subject, but with randomness to either progress or improve, not sure what extent endpoints needs. Also with an "improved" Visit domain, you can also have the responses correspond with each visit but then we run into the harominzation piece as consents/studcomp as previously mentioned

File: R/Raw_STUDCOMP.R [hunk 2]
```diff
@@ -70,8 +70,10 @@ compyn <- function(n, ...) {
          replace = TRUE)
 }
 
-completion_reason <- function(n, ...) {
-  rep("TERMINATION OF MEDICATION", n)
+compreas <- function(n, ...) {
+  sample(c("Lost to Follow-Up", "Death", "Withdrew Consent"),
```
Comment (zdz2101) [inline R/Raw_STUDCOMP.R:74]: If we're including `Withdrew Consent` it may result in inconsistencies with what comes out of `Consents` , can replace with "Adverse Events" (?) 

However, if you wanted them to be harmonized, it would depend on if both workflows was called into the generation which is the difficult part, haven't quite wrapped my head around that part yet.

File: R/generate_rawdata_for_single_study.R [hunk 3]
```diff
@@ -90,6 +90,11 @@ generate_rawdata_for_single_study <- function(SnapshotCount,
   pd_count <- subject_count * 3
   sdrgcomp_count <- ceiling(subject_count / 2)
   studcomp_count <- ceiling(subject_count / 10)
+  consents_count <- ceiling(subject_count / 75)
+  death_count <- ceiling(subject_count / 85)
+  visit_count <- subject_count * 4
```
Comment (zdz2101) [inline R/generate_rawdata_for_single_study.R:95]: I'm not entirely sure what this is doing, do you have a explanation for me? I was barely able to stitch visit together the first time I tried

File: R/generate_rawdata_for_single_study.R
Comment (lauramaxwell) [reply R/generate_rawdata_for_single_study.R:1]: yeah, i think this makes sense. We'd want to include `SUBJ` and `STUDY` in there as well- i'll add it to the example script

File: R/Raw_VISIT.R [hunk 4]
```diff
@@ -32,42 +32,50 @@ Raw_VISIT <- function(data, previous_data, spec, startDate, SnapshotCount, Snaps
...
+    default = list(n, possible_Visits)
   )
 
   res <- add_new_var_data(dataset, curr_spec, args, spec$Raw_VISIT, ...)
   return(res)
 }
 
-visit_date <- function(n, subjs, start_date, possible_Visits, SnapshotWidth,...) {
-  rep(generate_consecutive_random_dates(nrow(possible_Visits), start_date, period_to_days(SnapshotWidth)), length(subjs))
+subjid_invid <- function(n, Raw_SUBJ_data, ...) {
```
Comment (zdz2101) [inline R/Raw_VISIT.R:66]: whatever you did here is wizardry

**Review by zdz2101 — COMMENTED** [review]
couple thoughts

File: R/generate_rawdata_for_single_study.R
Comment (zdz2101) [reply R/generate_rawdata_for_single_study.R:1]: In theory it force grabs it anyway, see `generate_rawdata_for_single_study.R`, these are the "bare minimums" to assemble it. It kinda works as a reverse priority of the yamls

File: R/Raw_STUDCOMP.R (hunk 2 above)
Comment (lauramaxwell) [reply R/Raw_STUDCOMP.R:74]: In the endpoints package there are functions called `complete_consents()` and `complete_death()` that filter studcomp to "Withdrew Consent" and "Death", respectively, and then merged with their respective domains. I think these values are expected in the STUDCOMP data.

File: R/generate_rawdata_for_single_study.R [hunk 5]
```diff
@@ -137,6 +142,10 @@ generate_rawdata_for_single_study <- function(SnapshotCount,
         data_type == "Raw_SUBJ" ~ subject_count[snapshot_idx],
         data_type == "Raw_SDRGCOMP" ~ sdrgcomp_count[snapshot_idx],
         data_type == "Raw_STUDCOMP" ~ studcomp_count[snapshot_idx],
+        data_type == "Raw_Consents" ~ consents_count[snapshot_idx],
+        data_type == "Raw_Death" ~ death_count[snapshot_idx],
+        data_type == "Raw_VISIT" ~ visit_count[snapshot_idx],
```
Comment (lauramaxwell) [inline R/generate_rawdata_for_single_study.R:147]: assign n based on data type

File: R/generate_rawdata_for_single_study.R (hunk 3 above)
Comment (lauramaxwell) [reply R/generate_rawdata_for_single_study.R:95]: it's making it so that `n` for the visit data is 4x as big as the number of subjects in the snapshot. See comment [below](https://github.com/Gilead-BioStats/gsm.datasim/pull/44/files/79a682632f41fc64bfc83abd742cc9185624a714#r2019059348)

File: R/Raw_OverallResponse.R (hunk 1 above)
Comment (lauramaxwell) [reply R/Raw_OverallResponse.R:47]: ok, yeah- i'll probably need to do a bit of work on this one. looking closer at the old sample data in the endpoints package there are 241 (of 800 total) unique participants in this dataset with anywhere from 1 to 8 observations each.

we could harmonize with visit if we change the priority of this yaml to 2 and then feed in the Raw_Visit data to match up rs_dt with visit_dt (if that makes sense)

File: R/Raw_STUDCOMP.R (hunk 2 above)
Comment (zdz2101) [reply R/Raw_STUDCOMP.R:74]: Ahh yes I missed it in the first iteration, consents is a priority 2 with STUDCOMP as prerequisite to run, so there probably just needs to be a check to ensure if `Consents` is being generated, then `STUDCOMP` is required as well.

File: R/generate_rawdata_for_single_study.R (hunk 3 above)
Comment (zdz2101) [reply R/generate_rawdata_for_single_study.R:95]: I think I'm just getting lost between the number of visits thats being generated when you can also toggle something like `SnapshotCount` which affects it too? All I know is it seems to work so its fine by me

**Review by zdz2101 — APPROVED** [review]
In terms of a set of dataframes and assembling them this works, in terms of "working"/useful for endpoints I suppose we'll see after implementation?
